spring:
  application:
    name: watchBack
    version: 1.0.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      database: 0         # Redis数据库索引（默认为0）
      port: 6379
server:
  port: 9207

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.cjh.watching.watchback.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: false
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: watchToken
  # token 有效期（单位：秒） 默认一天天，-1 代表永久有效
  timeout: 86400
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9208/xxl-job-admin
    # 访问令牌，需要与XXL-JOB Admin控制台配置一致，如果为空则不验证
    accessToken: 
    executor:
      # 执行器名称，需要在XXL-JOB Admin控制台中配置
      appname: watchBack-executor
      # 执行器地址，为空则自动获取
      address:
      # 执行器IP，为空则自动获取
      ip:
      # 执行器端口
      port: 9999
      # 执行器日志路径
      logpath: ./logs/xxl-job
      # 日志保留天数
      logretentiondays: 30
logging:
  level:
    com.cjh.watching.watchback.mapper: debug
# Minio 配置
minio:
  endpoint:  http://localhost:9000
  accessKey: admin
  secretKey: admin123
  bucketName: watch
# RustFS 配置
rustfs:
  endpoint: http://localhost:9000
  accessKey: rustfsadmin
  secretKey: rustfsadmin
  region: us-east-1
  defaultBucket: watch
storage:
  service:
    type: rustfs